"""Dataclass contracts for the Clara pipeline. Plain dataclasses, no ORM."""

from dataclasses import dataclass, field
from typing import Optional, List
from enum import Enum


class InputType(Enum):
    TEXT = "text"
    AUDIO = "audio"
    IMAGE = "image"


@dataclass
class IncomingMessage:
    """Parsed message from Twilio POST."""
    from_number: str
    body: str
    media_url: Optional[str] = None
    media_type: Optional[str] = None
    input_type: InputType = InputType.TEXT
    timestamp: float = 0.0
    request_id: str = ""


@dataclass
class AckResponse:
    """TwiML returned as immediate HTTP 200."""
    message: str
    twiml_xml: str


@dataclass
class TranscriptResult:
    """Audio transcription result."""
    text: str
    language: str
    duration_ms: int
    success: bool
    error: Optional[str] = None


@dataclass
class CacheEntry:
    """One entry from demo_cache.json."""
    id: str
    patterns: List[str]
    match_mode: str  # "any_keyword" | "image_demo"
    idioma: str      # "fr" | "es" | "any"
    respuesta: str
    audio_file: Optional[str] = None


@dataclass
class CacheResult:
    """Cache lookup result."""
    hit: bool
    entry: Optional[CacheEntry] = None
    score: float = 0.0


@dataclass
class KBContext:
    """Context extracted from Knowledge Base for the LLM."""
    tramite: str
    datos: dict = field(default_factory=dict)
    fuente_url: str = ""
    verificado: bool = False


@dataclass
class LLMResponse:
    """Response generated by Gemini."""
    text: str
    language: str
    duration_ms: int
    from_cache: bool
    success: bool
    error: Optional[str] = None


@dataclass
class FinalResponse:
    """Final message sent to user via Twilio REST."""
    to_number: str
    body: str
    media_url: Optional[str] = None
    source: str = "cache"  # "cache" | "llm" | "fallback"
    total_ms: int = 0
